name: Generate snake animation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Generated Files
        run: |
          echo "Checking dist directory..."
          if [ -d "dist" ]; then
            echo "Contents of dist:"
            ls -l dist
          else
            echo "dist directory does not exist."
            exit 1
          fi

      - name: Validate Build Directory
        run: |
          if [ ! -d "dist" ] || [ ! -f "dist/snake.svg" ]; then
            echo "Build directory or file not found!"
            exit 1
          fi

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
