name: Generate snake animation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate GitHub Username
        run: echo "GitHub Username:${{ github.repository_owner }}"

      - name: Generate snake.svg (Debug Mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: generate

      - name: Debug Action Output
        run: echo "Action output:${{ steps.generate.outputs }}"

      - name: Debug Working Directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing contents:"
          ls -la

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
